language: php

sudo: false

#cache:
#  directories:
#    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

php:
  - 5.6
  - 7.0

install:
  - composer self-update
  - DATABASE_DRIVER='pdo_sqlite' DATABASE_PATH='%kernel.root_dir%/app.sqlite' composer install --prefer-source --no-interaction

script:
  - php bin/phpcs -p --standard=PSR2 --extensions=php src
  - phpunit -c app/
