language: php

sudo: false

#cache:
#  directories:
#    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

php:
  - 5.6
  - 7.0

install:
  - composer self-update
  - DATABASE_DRIVER='pdo_sqlite' DATABASE_PATH='%kernel.root_dir%/app.sqlite' composer install --prefer-source --no-interaction
  - curl http://get.sensiolabs.org/php-cs-fixer.phar -o php-cs-fixer

script:
  - php php-cs-fixer fix src/ --dry-run -vv
  - phpunit -c app/
