language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.app_cache

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

php:
  - 5.6
  - 7.0

before_install:
  - mkdir -p $HOME/.app_cache

install:
  - mv $HOME/.app_cache/.php_cs.cache ./.php_cs.cache 2>/dev/null || true
  - composer self-update
  - DATABASE_DRIVER='pdo_sqlite' DATABASE_PATH='%kernel.root_dir%/app.sqlite' composer install --prefer-source --no-interaction
  - curl http://get.sensiolabs.org/php-cs-fixer.phar -o php-cs-fixer

script:
  - php php-cs-fixer fix --no-interaction --dry-run --diff -vvv
  - php bin/phpunit -c app/

after_script:
  - mv ./.php_cs.cache $HOME/.app_cache/.php_cs.cache 2>/dev/null || true
